# Generated by Django 6.0.3 on 2026-03-10 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                (
                    'visibilidad',
                    models.CharField(
                        choices=[('publico', 'Público'), ('privado', 'Privado')],
                        default='privado',
                        max_length=10,
                    ),
                ),
                (
                    'estado',
                    models.CharField(
                        choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')],
                        default='activo',
                        max_length=15,
                    ),
                ),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                (
                    'creador',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='proyectos_creados',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Epica',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('pendiente', 'Pendiente'),
                            ('en progreso', 'En Progreso'),
                            ('terminado', 'Terminado'),
                        ],
                        default='pendiente',
                        max_length=15,
                    ),
                ),
                (
                    'proyecto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='epicas',
                        to='api.proyecto',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('nombre', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('planeado', 'Planeado'),
                            ('activo', 'Activo'),
                            ('terminado', 'Terminado'),
                        ],
                        default='planeado',
                        max_length=15,
                    ),
                ),
                (
                    'proyecto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sprints',
                        to='api.proyecto',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaUsuario',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                (
                    'prioridad',
                    models.CharField(
                        choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')],
                        default='media',
                        max_length=10,
                    ),
                ),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('pendiente', 'Pendiente'),
                            ('en progreso', 'En Progreso'),
                            ('en pruebas', 'En Pruebas'),
                            ('terminado', 'Terminado'),
                        ],
                        default='pendiente',
                        max_length=15,
                    ),
                ),
                (
                    'epica',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='historias',
                        to='api.epica',
                    ),
                ),
                (
                    'sprint',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='historias',
                        to='api.sprint',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('titulo', models.CharField(max_length=200)),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('pendiente', 'Pendiente'),
                            ('en progreso', 'En Progreso'),
                            ('terminado', 'Terminado'),
                        ],
                        default='pendiente',
                        max_length=15,
                    ),
                ),
                (
                    'asignado_a',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='tareas_asignadas',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'historia',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tareas',
                        to='api.historiausuario',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoMiembro',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'rol_proyecto',
                    models.CharField(
                        choices=[('dueño', 'Dueño'), ('colaborador', 'Colaborador')],
                        default='colaborador',
                        max_length=20,
                    ),
                ),
                (
                    'proyecto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='miembros',
                        to='api.proyecto',
                    ),
                ),
                (
                    'usuario',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='proyectos_pertenecientes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'unique_together': {('proyecto', 'usuario')},
            },
        ),
    ]
