# Generated by Django 4.2.24 on 2026-03-10 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_historiausuario_asignado_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='proyecto',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='historias',
                to='api.proyecto',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tareas',
                to='api.proyecto',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='epica',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='historias',
                to='api.epica',
            ),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='historia',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tareas',
                to='api.historiausuario',
            ),
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                (
                    'prioridad',
                    models.CharField(
                        choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')],
                        default='media',
                        max_length=10,
                    ),
                ),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('pendiente', 'Pendiente'),
                            ('en progreso', 'En Progreso'),
                            ('terminado', 'Terminado'),
                        ],
                        default='pendiente',
                        max_length=15,
                    ),
                ),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                (
                    'asignado_a',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='bugs_asignados',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'proyecto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bugs',
                        to='api.proyecto',
                    ),
                ),
                (
                    'sprint',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='bugs',
                        to='api.sprint',
                    ),
                ),
            ],
        ),
    ]
