# Generated by Django 4.2.24 on 2026-03-10 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_historiausuario_proyecto_tarea_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'especialidades',
                    models.TextField(blank=True, help_text='Comprimidas por comas o JSON'),
                ),
                ('bio', models.TextField(blank=True)),
                (
                    'usuario',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='perfil',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
