# Generated by Django 4.2.24 on 2026-03-12 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_profile_foto_perfil_alter_adjunto_id_alter_bug_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionProyecto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'rol_invitado',
                    models.CharField(
                        choices=[('colaborador', 'Colaborador'), ('lector', 'Lector')],
                        default='colaborador',
                        max_length=20,
                    ),
                ),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            ('pendiente', 'Pendiente'),
                            ('aceptada', 'Aceptada'),
                            ('rechazada', 'Rechazada'),
                        ],
                        default='pendiente',
                        max_length=15,
                    ),
                ),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                (
                    'proyecto',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invitaciones',
                        to='api.proyecto',
                    ),
                ),
                (
                    'usuario_invitado',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invitaciones_recibidas',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'usuario_remitente',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invitaciones_enviadas',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
