# Generated by Django 4.2.24 on 2026-03-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_invitacionproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='color',
            field=models.CharField(default='#10B981', max_length=7),
        ),
    ]
