# Generated by Django 4.2.24 on 2026-03-12 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_sprint_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(
                choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')],
                default='media',
                max_length=10,
            ),
        ),
    ]
