# Generated by Django 4.2.24 on 2026-03-19 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_tarea_descripcion_tarea_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='sprint',
        ),
        migrations.AddField(
            model_name='bug',
            name='historia',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bugs',
                to='api.historiausuario',
            ),
        ),
        migrations.AlterField(
            model_name='bug',
            name='estado',
            field=models.CharField(
                choices=[
                    ('nuevo', 'Nuevo'),
                    ('en progreso', 'En Progreso'),
                    ('corregido', 'Corregido'),
                    ('cerrado', 'Cerrado'),
                ],
                default='nuevo',
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name='invitacionproyecto',
            name='rol_invitado',
            field=models.CharField(
                choices=[('colaborador', 'Colaborador')], default='colaborador', max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='proyectomiembro',
            name='rol_proyecto',
            field=models.CharField(
                choices=[('dueño', 'Dueño'), ('colaborador', 'Colaborador')],
                default='colaborador',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tareas_directas',
                to='api.proyecto',
            ),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
