# Generated by Django 6.0.3 on 2026-04-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_bug_sprint_bug_historia_alter_bug_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='horas_estimadas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bug',
            name='horas_reales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='horas_estimadas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='horas_reales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='repositorio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='horas_estimadas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tarea',
            name='horas_reales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
