# Generated by Django 4.2.24 on 2026-04-30 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_bug_horas_estimadas_bug_horas_reales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='beneficio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='necesidad',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='rol',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='talla',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=5),
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CeremoniaScrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('daily', 'Daily Scrum'), ('review', 'Sprint Review'), ('planning', 'Sprint Planning'), ('retro', 'Sprint Retrospective')], max_length=20)),
                ('fecha', models.DateTimeField()),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En Curso'), ('finalizada', 'Finalizada')], default='programada', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('participantes', models.ManyToManyField(blank=True, related_name='ceremonias_asistidas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceremonias', to='api.proyecto')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceremonias', to='api.sprint')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
