# Generated by Django 4.2.24 on 2026-04-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_historiausuario_beneficio_historiausuario_necesidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremoniascrum',
            name='reunion_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
