# Generated by Django 4.2.24 on 2026-04-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_ceremoniascrum_reunion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sprint',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
    ]
