# Generated by Django 4.2.24 on 2026-05-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_historiausuario_puntos_sprint_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
