# Generated by Django 4.2.24 on 2026-05-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_historiausuario_archivado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiausuario',
            name='archivado',
        ),
        migrations.AlterField(
            model_name='historiausuario',
            name='talla',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=5, null=True),
        ),
    ]
